//main Layout

export const SHORTMENU_SHOW_CHANGE = 'SHORTMENU_SHOW_CHANGE';
export const MODULELIST_SHOW_CHANGE = 'MODULELIST_SHOW_CHANGE';
export const SIDEMENU_SHOW_CHANGE = 'SIDEMENU_SHOW_CHANGE';